name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from repository
    - name: Check out code
      uses: actions/checkout@v4
      with:
        python-version: "3.10"

    # Step 2: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 3: Run tests
    - name: Run tests
      run: pytest